// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcKOGEE2xNguGAhfGatf4eqnRpSgGng8',
    appId: '1:392198872561:web:b2079f2d1094714223f850',
    messagingSenderId: '392198872561',
    projectId: 'final-projectmotobike',
    authDomain: 'final-projectmotobike.firebaseapp.com',
    storageBucket: 'final-projectmotobike.appspot.com',
    measurementId: 'G-46Z6W68R6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEowya6ko0ihjQvjhOQoGIO3Dhf7RJuMk',
    appId: '1:392198872561:android:3db7d06bead251e023f850',
    messagingSenderId: '392198872561',
    projectId: 'final-projectmotobike',
    storageBucket: 'final-projectmotobike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlmpUgS4SXPcR62WIT8EVbKuw3ktCoslA',
    appId: '1:392198872561:ios:dff3947a31ef473e23f850',
    messagingSenderId: '392198872561',
    projectId: 'final-projectmotobike',
    storageBucket: 'final-projectmotobike.appspot.com',
    iosBundleId: 'com.example.finalprojectMotobikeCs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlmpUgS4SXPcR62WIT8EVbKuw3ktCoslA',
    appId: '1:392198872561:ios:dff3947a31ef473e23f850',
    messagingSenderId: '392198872561',
    projectId: 'final-projectmotobike',
    storageBucket: 'final-projectmotobike.appspot.com',
    iosBundleId: 'com.example.finalprojectMotobikeCs',
  );
}
